### ISSUE TITLE
Add security to web app

### ISSUE THREAD

**Issue by robert-clegg-tessella** [ukaea/ditto#27]
Require access token to run any commands

Service to connect with LDAP

**Comment by daniel-hunt-tessella** [comment]
**Acceptance Criteria**
This can be tested by checking that every API route requires a Basic Auth header with the information in the `security_configuration.ini file` in order to run - otherwise the API returns a 401 Not Authorised response.

**Testing**
Each of the six API routes copydir, copyupdate, copynew, listpresent, deletefile and createbucket each require an authentication header in order to work successfully. Otherwise a 401 status code is responded
